version: "3.3"
services:
  app:
    container_name: mttw-app
    build:
      context: ""
      dockerfile: Dockerfile
      args:
        - VERSION=${VERSION}
        - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
    environment:
      SERVER_PORT: ${PORT}
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_ACTIVE_MQ_BROKER-URL: ${MB_URL}
      SPRING_ACTIVE_MQ_USER: ${MB_USER}
      SPRING_ACTIVE_MQ_PASSWORD: ${MB_PASSWORD}
    network_mode: "host"