FROM openjdk:8u212-jdk-slim

ARG SERVER_PORT
ARG SPRING_DATASOURCE_URL
ARG SPRING_DATASOURCE_USERNAME
ARG SPRING_DATASOURCE_PASSWORD
ARG SPRING_ACTIVE_MQ_BROKER-URL
ARG SPRING_ACTIVE_MQ_USER
ARG SPRING_ACTIVE_MQ_PASSWORD

VOLUME /tmp

EXPOSE ${SERVER_PORT}

ENV SERVER_PORT ${SERVER_PORT}
ENV SPRING_DATASOURCE_URL ${SPRING_DATASOURCE_URL}
ENV SPRING_DATASOURCE_USERNAME ${SPRING_DATASOURCE_USERNAME}
ENV SPRING_DATASOURCE_PASSWORD ${SPRING_DATASOURCE_PASSWORD}
ENV SPRING_ACTIVE_MQ_BROKER-URL ${SPRING_ACTIVE_MQ_BROKER-URL}
ENV SPRING_ACTIVE_MQ_USER ${SPRING_ACTIVE_MQ_USER}
ENV SPRING_ACTIVE_MQ_PASSWORD ${SPRING_ACTIVE_MQ_PASSWORD}

ADD https://github.com/rsaestrela/message-to-the-world/releases/latest/download/mttw-0.0.1-SNAPSHOT.jar mttw.jar

ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/mttw.jar"]